name: Terraform Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AMI_ID: ${{ secrets.AMI_ID }}
        run: |
          terraform apply -auto-approve \
          -var "aws_region=ap-south-1" \
          -var "aws_access_key=${AWS_ACCESS_KEY}" \
          -var "aws_secret_key=${AWS_SECRET_KEY}" \
          -var "ami_id=${AMI_ID}" \
          -var "instance_type=t2.micro"